In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
print("# GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

TensorFlow version: 2.4.1
# GPUs Available:  1


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.38525608,  0.5564548 ,  0.2224456 , -0.47924384,  0.45285183,
        -0.04097714,  0.0190098 , -0.21853194,  1.0644913 ,  0.057607  ]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.10972504, 0.1302136 , 0.0932391 , 0.04622301, 0.11739842,
        0.0716465 , 0.07607589, 0.0599907 , 0.21641824, 0.07906961]],
      dtype=float32)

In [7]:

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 707us/step - loss: 0.4871 - accuracy: 0.8540
Epoch 2/5
1875/1875 [==============================] - 1s 692us/step - loss: 0.1529 - accuracy: 0.9546
Epoch 3/5
1875/1875 [==============================] - 1s 688us/step - loss: 0.1092 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 1s 678us/step - loss: 0.0841 - accuracy: 0.9751
Epoch 5/5
1875/1875 [==============================] - 1s 776us/step - loss: 0.0709 - accuracy: 0.9774


In [8]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0692 - accuracy: 0.9787


[0.06917382031679153, 0.9786999821662903]

In [9]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.49623042e-06, 3.87818453e-08, 5.06454580e-06, 2.57211505e-04,
        7.39805231e-11, 9.69983603e-07, 8.35028932e-13, 9.99721348e-01,
        2.26171423e-07, 1.36563149e-05],
       [9.95072358e-10, 7.50101244e-05, 9.99913335e-01, 1.12148855e-05,
        1.41790496e-13, 3.51072487e-07, 1.65940889e-07, 1.77396465e-14,
        7.87158516e-09, 1.49411542e-11],
       [1.34599205e-07, 9.99558151e-01, 1.60192663e-04, 3.64727239e-05,
        4.35690936e-06, 3.92696120e-06, 4.15960349e-05, 1.55259477e-04,
        3.98402881e-05, 9.70680745e-08],
       [9.99588072e-01, 6.20768237e-09, 1.81307943e-04, 2.65010442e-07,
        6.98173892e-08, 1.23844495e-06, 2.25318927e-05, 1.03976686e-06,
        1.30719358e-09, 2.05401418e-04],
       [6.58553199e-06, 5.56943114e-09, 1.93222490e-06, 1.25008324e-08,
        9.95889604e-01, 8.30614908e-07, 2.00159570e-06, 7.34767991e-06,
        1.49775406e-06, 4.09016013e-03]], dtype=float32)>